# docker-compose.yml
version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,apigateway,dynamodb,s3,ssm,cloudformation,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
